from LinkedlistC import LinkedlistC

a = LinkedlistC()
a.addNode("3")
a.addNode("4")
a.addNode("5")
a.addNode("1")
print(a)
a.delete("1")
print(a)

print("Insertar 10 antes de 5")
a.insert_before("5","10")
print(a)
b = LinkedlistC()
b.addNode("80")
b.addNode("-3")
b.addNode("1")
print("B")
print(b)
print("Insertar b en a (ordenado) ")
a.insertar_lista(b)
print(a)

c = LinkedlistC()
c.addNode("0")
c.addNode("8")
print("C")
print(c)
print("Agregar a en c despues de pos 0")
c.insertar_lista2(a, 0)
print(c)

x = LinkedlistC()
print("X")
x.addNode2(3, 2, 2, 3)
x.addNode2(1, 2,1,2)
x.addNode2(3,0,0,0)
x.recorrer2()

y = LinkedlistC()
print("Y")
y.addNode2(-4,2,1,3)
y.addNode2(-1,2,1,2)
y.addNode2(5,0,0,0)
y.recorrer2()
print("X ")
x.coeficientes(y)
x.recorrer2()

